version: 1.0
os: linux
files:
 - source: .
   destination: /home/projects/ioasys-challenge
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: root