version: "3.3"

services:
  
  database_joinme:
    image: postgres
    container_name: database_joinme
    restart: always
    ports: 
      - "65435:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres    
    env_file:
      - .env
  app_ioasys:
    build: .
    container_name: app_ioasys
    restart: always
    ports: 
      - ${PORT}:${PORT}   
    volumes: 
      - .:/usr/app
      - /usr/app/node_modules 
    links: 
      - redis
      - database_joinme
    depends_on:
      - redis
      - database_joinme
    env_file:
      - .env
  redis:
    image: 'redis:alpine'
    restart: always
    container_name: redis
    ports:
      - 6380:6379

volumes:
  pgdata:
    driver: local