version: "3.3"

services:
  
  app_ioasys:
    build: .
    container_name: app_ioasys
    restart: always
    ports: 
      - ${PORT}:${PORT}   
    volumes: 
      - .:/usr/app
      - /usr/app/node_modules 
    links: 
      - redis
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: 'redis:alpine'
    restart: always
    container_name: redis
    ports:
      - 6380:6379

volumes:
  pgdata:
    driver: local